// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.23.0

package db

import (
	"time"

	"github.com/google/uuid"
)

type Absence struct {
	ID           int64      `json:"id"`
	UserID       int64      `json:"user_id"`
	StartTime    time.Time  `json:"start_time"`
	EndTime      *time.Time `json:"end_time"`
	Reason       string     `json:"reason"`
	Paid         bool       `json:"paid"`
	CreatedAt    time.Time  `json:"created_at"`
	UpdatedAt    *time.Time `json:"updated_at"`
	ApprovedByID *int64     `json:"approved_by_id"`
}

type Company struct {
	ID        int64      `json:"id"`
	Name      string     `json:"name"`
	CreatedAt time.Time  `json:"created_at"`
	UpdatedAt *time.Time `json:"updated_at"`
}

type Entry struct {
	ID        int64      `json:"id"`
	UserID    int64      `json:"user_id"`
	StartTime time.Time  `json:"start_time"`
	EndTime   *time.Time `json:"end_time"`
	CreatedAt time.Time  `json:"created_at"`
	UpdatedAt *time.Time `json:"updated_at"`
}

type Session struct {
	ID           uuid.UUID `json:"id"`
	Username     string    `json:"username"`
	RefreshToken string    `json:"refresh_token"`
	UserAgent    string    `json:"user_agent"`
	ClientIp     string    `json:"client_ip"`
	IsBlocked    bool      `json:"is_blocked"`
	ExpiresAt    time.Time `json:"expires_at"`
	CreatedAt    time.Time `json:"created_at"`
}

type Team struct {
	ID        int64      `json:"id"`
	Name      string     `json:"name"`
	ManagerID *int64     `json:"manager_id"`
	CreatedAt time.Time  `json:"created_at"`
	UpdatedAt *time.Time `json:"updated_at"`
}

type User struct {
	ID        int64      `json:"id"`
	Username  string     `json:"username"`
	Email     string     `json:"email"`
	Name      string     `json:"name"`
	Surname   string     `json:"surname"`
	CompanyID *int64     `json:"company_id"`
	Password  string     `json:"password"`
	Gender    string     `json:"gender"`
	BirthDate time.Time  `json:"birth_date"`
	CreatedAt time.Time  `json:"created_at"`
	UpdatedAt *time.Time `json:"updated_at"`
	// ISO-2 language code
	Language string `json:"language"`
	// ISO-2 Country code
	Country *string `json:"country"`
	// Timezone name
	Timezone  string `json:"timezone"`
	ManagerID *int64 `json:"manager_id"`
	TeamID    *int64 `json:"team_id"`
	Role      string `json:"role"`
}
